// State -> YAML serializer for the map editor. Mirrors the format of
// data/maps/skirmish.yaml so output is hand-editable and round-trips
// cleanly through the loader.

import { BattleMap } from "../data/schema";

export function mapToYaml(map: BattleMap): string {
  const lines: string[] = [];
  lines.push(`# Generated by the map editor at ${new Date().toISOString().slice(0, 19).replace("T", " ")}`);
  lines.push(`id: ${map.id}`);
  lines.push(`name: ${quoteIfNeeded(map.name)}`);
  lines.push(`size: { cols: ${map.size.cols}, rows: ${map.size.rows} }`);
  lines.push("");
  lines.push("tiles:");
  for (const row of map.tiles) {
    lines.push(`  - "${row.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`);
  }
  lines.push("");
  lines.push("units:");
  for (const u of map.units) {
    lines.push(`  - { template: ${u.template}, at: [${u.at[0]}, ${u.at[1]}] }`);
  }
  lines.push("");
  lines.push(`victory: ${map.victory}`);
  lines.push("");
  return lines.join("\n");
}

function quoteIfNeeded(s: string): string {
  if (/^[A-Za-z0-9 _.,'-]+$/.test(s)) return s;
  return JSON.stringify(s);
}
